# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Appstore iOS 11' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Appstore iOS 11
  
  pod 'Cards'
  pod 'Kingfisher', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'

end
